# Generated by Django 2.2.5 on 2019-10-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.DecimalField(decimal_places=2, max_digits=10, primary_key=True, serialize=False)),
                ('phone_name', models.CharField(default='', max_length=50)),
                ('phone_link', models.CharField(max_length=50)),
                ('phone_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
