# Generated by Django 2.2.5 on 2019-10-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_phone_n_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_n_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
